library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -isrc
  - -Widentities
tests:
  notion-ocr-plugin-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-ocr-plugin
copyright: 2019 Yannick Gladow
maintainer: yannick.gladow@gmail.com
dependencies:
- transformers
- temporary
- mtl
- stm
- wai-cors
- wai
- warp
- servant-server
- aeson
- time
- text
- servant
- servant-elm
- elm-bridge
- notion-ocr
- base >= 4.7 && < 5
name: notion-ocr-plugin
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Yannick Gladow
github: yannick-cw/notion-ocr-plug
license: BSD3
executables:
  notion-ocr-plugin-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-ocr-plugin
  elm-gen-exe:
    source-dirs: gen
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-ocr-plugin
description: Please see the README on GitHub at <https://github.com/githubuser/notion-ocr-plugin#readme>
